### ISSUE TITLE
Not installing on Windows 10

### ISSUE THREAD

**Issue by Paul-Kim** [medibloc/medjs#1]
아래 명령어로 설치가 안되네요.

```cmd
npm install medjs
```

Environment :
- Windows 10 pro x64
- Python : Anaconda virtual env with python 3.6.4 in "E:\ProgramData\Anaconda3\python.exe"
- npm@5.6.0 is installed in "C:\Program Files\nodejs\node_modules\npm"

Error messeages are like below : 
```cmd
(base) E:\User\KM\Documents\git\Medibloc\node_modules\scrypt>if not defined npm_config_node_gyp  
 (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp- bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program  Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )  
gyp ERR! configure error  
gyp ERR! stack Error: Can't find Python executable "E:\ProgramData\Anaconda3\python.EXE", you can set the PYTHON env variable.  
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)  
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)  
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29  
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)  
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"  
gyp ERR! cwd E:\User\KM\Documents\git\Medibloc\node_modules\scrypt  
gyp ERR! node -v v8.11.4  
gyp ERR! node-gyp -v v3.6.2  
gyp ERR! not ok  
npm WARN enoent ENOENT: no such file or directory, open 'E:\User\KM\Documents\git\Medibloc\package.json'
npm WARN Medibloc No description  
npm WARN Medibloc No repository field.  
npm WARN Medibloc No README data  
npm WARN Medibloc No license field.  
  
npm ERR! code ELIFECYCLE  
npm ERR! errno 1  
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`  
npm ERR! Exit status 1  
npm ERR!  
npm ERR! Failed at the scrypt@6.0.3 install script.  
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.  
  
npm ERR! A complete log of this run can be found in:  
npm ERR!     C:\Users\kmc55\AppData\Roaming\npm-cache\_logs\2018-08-23T06_01_10_413Z-debug.log  
```

```cmd
set PYTHON=E:\ProgramData\Anaconda3\python.exe
```
or
```cmd
set PYTHON=C:\Users\kmc55\AppData\Local\Programs\Python\Python36\python.exe
```
등으로 바꾸어도 여전히 설치가 안되네요. 어떻게 하면 좋을까요?
참고로 파이썬은 
```cmd
(base) E:\User\KM\Documents\git\Medibloc>where python
E:\ProgramData\Anaconda3\python.exe
C:\Users\kmc55\AppData\Local\Programs\Python\Python36\python.exe
```
여기 두군데 설치되어 있습니다.

**Comment by ggomma** [comment]
안녕하세요. 문의하신 오류는 node-gyp 모듈이 python 3.x.x 버전을 지원하지 않기 때문에 발생합니다.

python 2.7 버전을 설치하신 후 다시 시도해보시기 바랍니다.

node-gyp : https://www.npmjs.com/package/node-gyp

**Comment by ggomma** [comment]
추가 진행 상황이 없어 이슈 닫습니다.

**Comment by Paul-Kim** [comment]
Python 2.7 환경에서 정상적으로 설치됩니다. 감사합니다.
